### ISSUE TITLE
Undefined index in context.php

### ISSUE THREAD

**Issue by philcross** [sebastianbergmann/recursion-context#5]
We've suddenly got a lot a lot of issues with context.php issuing an undefined index notice:

```
notice: Undefined offset: 1 in vendor/sebastian/recursion-context/src/Context.php line 141
```

Looks like the latest branch 1.0.3 has broken it, reverted to 1.0.2 and is working again.

**Comment by sebastianbergmann** [comment]
@bwoebi Can you have a look?

**Comment by iMega** [comment]
See https://github.com/sebastianbergmann/recursion-context/pull/6

**Comment by weierophinney** [comment]
I can confirm; see a [recent zend-expressive test run](https://travis-ci.org/zendframework/zend-expressive/jobs/175779891#L272). Tests pass on previous versions, but not against 1.0.3.

**Comment by bwoebi** [comment]
Weird, I cannot reproduce this locally (I tried with zend-expressive and recursion context 1.0.3). Also, how can index 1 not be set? array_splice() is returning an array keyed incrementally from 0 up (by default).

And the line there is `count($end) != 2 || $end[1] !== 2 ? false : $end[0]` … i.e. if there's less than two elements, `$end[1]` should not be accessed?!

**Comment by bwoebi** [comment]
… oh, array_slice is preserving non-numeric keys… yeah, #6 should fix it then.

**Comment by khoanhd** [comment]
it works right now, thanks.
