### ISSUE TITLE
Missing version tag for 1.0.3

### ISSUE THREAD

**Issue by SvenRtbg** [sebastianbergmann/recursion-context#9]
Hi there, I think this lib once had a version 1.0.3 tagged at commit 79860854756415e1cec8d186c9cf261cafd87dfc

Automated updates catched this version and put it into use for my software, but this repository does not have the tag anymore. Where is it?

**Comment by sebastianbergmann** [comment]
I do not remember deleting this tag, if it ever existed.

**Comment by sebastianbergmann** [comment]
I do not see a single PHAR release of PHPUnit https://phar.phpunit.de/ that has an 1.0.3 release of this component bundled.

**Comment by sebastianbergmann** [comment]
@seldaek Does Packagist have an audit trail for looking up whether an 1.0.3 release existed at some point?

**Comment by SvenRtbg** [comment]
There seems to be an incompatibility issue #7 referring to version 1.0.4, which also does not exist anymore.

**Comment by Seldaek** [comment]
@sebastianbergmann nope we don't keep track of this as it's kinda idempotent and re-running generally yields the same result unless you wipe tags of course..

**Comment by SvenRtbg** [comment]
Look at this comment, suggesting you did indeed delete the tags: https://github.com/sebastianbergmann/recursion-context/issues/8#issuecomment-261696844

Note that whenever a release breaks backwards compatibility, deleting the tags is almost always worse that tagging the previous release with a higher patch level. I.E. if 1.0.2 was good, and all 1,0.3 and 1.0.4 were bad, tagging the 1.0.2 commit again as 1.0.5 would repair all update pain.

Doing just that now will enable everyone that periodically (i.e. daily) scans Packagist and updates dependencies to recover nicely.

**Comment by sebastianbergmann** [comment]
Ah, right. Now I remember. Sorry about that.

**Comment by sebastianbergmann** [comment]
Tag `1.0.5` has been created.
